---
- hosts: node
  become: yes
  tasks:
   - name: Install docker-ce (centos) via amazon-linux-extras packages
     shell: "amazon-linux-extras install docker=18.06.1 -y"

   - name: Enable Docker CE service at startup
     service:
      name: docker
      state: started
      enabled: yes

   - name: pulling image
     shell: docker pull vishnupriya8/simple
